# .github/workflows/benchmarks.yml
name: Performance Benchmarks (Bun)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0' # Cada domingo a las 3 AM UTC

jobs:
  benchmarks:
    name: Run Performance Benchmarks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - name: Remove bun.lockb (if exists)
        run: |
          if [ -f bun.lockb ]; then
            rm bun.lockb
          fi
        shell: bash

      - name: Install latest SpectralLogs clean
        run: |
          bun add spectrallogs@latest


      - name: Build project (TypeScript)
        shell: bash
        run: |
          if [ -f tsconfig.json ]; then
            bun run tsc
          fi

      - name: Run benchmark suite (original)
        run: bun run benchmarks/benchmarks.ts
        env:
          NODE_ENV: production

      - name: Run improved benchmark suite
        run: bun --expose-gc run benchmarks/improved-benchmarks.ts
        env:
          NODE_ENV: production
        timeout-minutes: 10

      - name: Upload benchmark results (original)
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ matrix.os }}
          path: benchmarks/results/benchmark-results.json
          retention-days: 30

      - name: Upload improved benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: improved-benchmark-results-${{ matrix.os }}
          path: benchmarks/results/improved-benchmark-results.json
          retention-days: 30

  benchmark-report:
    name: Generate Benchmark Report
    runs-on: ubuntu-latest
    needs: benchmarks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download benchmark artifacts (original)
        uses: actions/download-artifact@v4
        with:
          path: benchmarks/results
          pattern: benchmark-results-*
          merge-multiple: true

      - name: Download improved benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          path: benchmarks/results
          pattern: improved-benchmark-results-*
          merge-multiple: true

      - name: Install dependencies
        run: bun install

      - name: Generate benchmark report (original)
        run: |
          bun run scripts/generate-benchmark-report.js

      - name: Generate improved benchmark report
        run: |
          if [ -f benchmarks/results/improved-benchmark-results.json ]; then
            bun run scripts/generate-improved-report.js
          else
            echo "Improved benchmark results not found, skipping improved report."
          fi

      - name: Verify report generation
        shell: bash
        run: |
          if [ ! -f benchmarks/results/benchmark-report.md ] && [ ! -f benchmarks/results/improved-benchmark-report.md ]; then
            echo "::warning::No benchmark reports generated, skipping."
          fi

      - name: Post report as PR comment (if applicable)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            // Priorizar el reporte mejorado si existe
            let reportPath = 'benchmarks/results/improved-benchmark-report.md';
            if (!fs.existsSync(reportPath)) {
              reportPath = 'benchmarks/results/benchmark-report.md';
            }
            if (!fs.existsSync(reportPath)) {
              console.log("No benchmark report found, skipping comment.");
            } else {
              const report = fs.readFileSync(reportPath, 'utf8');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: report
              });
            }

      - name: Upload benchmark reports
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-reports
          path: |
            benchmarks/results/benchmark-report.md
            benchmarks/results/improved-benchmark-report.md
          retention-days: 30

  performance-check:
    name: Performance Regression Check
    runs-on: ubuntu-latest
    needs: benchmarks
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Download benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: benchmark-results-*
          path: benchmarks/results
          merge-multiple: true

      - name: Download improved benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: improved-benchmark-results-*
          path: benchmarks/results
          merge-multiple: true

      - name: Install dependencies
        run: bun install

      - name: Check for performance regressions
        run: bun run scripts/check-performance-regressions.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}